### ISSUE TITLE
'list' object is not callable

### ISSUE THREAD

**Issue by mfakane** [suzutan/pyture-remo#1]
```
Exception has occurred: TypeError
'list' object is not callable
  File "...", line 5, in <module>
    appliance.signals()
```

https://github.com/suzutan/pyture-remo/commit/6d9ef2b755b9dbbd145394369e33b10c410d4591 にて `find_signals()` が `signals()` とリネームされましたが、既に存在するメンバ変数 `signals` と名前が衝突しているため呼び出すことができません。

https://github.com/suzutan/pyture-remo/blob/6d9ef2b755b9dbbd145394369e33b10c410d4591/pyture_remo/appliance.py#L30-L31

メンバ変数 `signals` への直接のアクセスを正式な方法とし getter メソッドを廃止する、もしくは getter となるメソッドを介したアクセスに限定するためにメンバ変数を `__signals` などとリネームし外部からのアクセスを不可能にする、などの対応が必要です。

**Comment by suzutan** [comment]
seyana.

**Comment by suzutan** [comment]
fix tomorrow
